### ISSUE TITLE
icepll lacks an option for creating SB_PLL40_PAD modules

### ISSUE THREAD

**Issue by olofk** [YosysHQ/icestorm#190]
PLLs that are fed from dedicated clock inputs need to be instantiated as SB_PLL40_PAD, but icepll only supports SB_PLL40_CORE modules. I think it works to instantiate the correct module manually and `include the parameters that icepll creates, but it would be handy to have this built into icepll as a switch

Or can this be done manually by using the _CORE primitive and placing a buffer before or after the clock input/output? Couldn't figure that out from the PLL documentation

**Comment by Nufflee** [comment]
@cliffordwolf Any updates on this?

**Comment by mmicko** [comment]
Fixed by merging mentioned PR, changed help message
