### ISSUE TITLE
Additional modules needed for build on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by terrillmoore** [YosysHQ/icestorm#191]
I needed to add the following when installing on Ubuntu 16.0.4; these were only needed for nextpnr (but I built that before yosys, so some might have been needed for yosys, too).

For simplicity, here's the combined command for installing what's needed:

```shell
sudo apt install cmake libboost-filesystem-dev libboost-thread-dev \
    libboost-program-options-dev libboost-python-dev
```

**Comment by mmicko** [comment]
Instructions to use these packages is already on nextpnr GitHub readme file
