### ISSUE TITLE
Compiling nextpnr on ubuntu 14.04

### ISSUE THREAD

**Issue by drtrigon** [YosysHQ/icestorm#199]
As mentioned already in https://github.com/cliffordwolf/icestorm/issues/191 compilation steps of nextpnr need `cmake` also, BUT when you try to use the version from the ubuntu repos you get:
```
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.3 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
```

**Comment by mmicko** [comment]
This is nextpnr issue, but anyway, you can use CMake binaries from official page https://cmake.org/download/ in case you are using very old distribution like Ubuntu 14.04
