### ISSUE TITLE
make install error on compile timings-lp384.cc on OSX - exit not defined

### ISSUE THREAD

**Issue by williamsharkey** [YosysHQ/icestorm#216]
I am unable to make install the icetools on OSX 10.12.6

I think there may need to be an additional header added: 
```#include <stdlib.h>```
cf: https://github.com/google/re2/issues/111

Here is my error message:

```
python3 timings.py lp384 > timings-lp384.cc
c++ -MD -O2  -Wall -std=c++11 -I/usr/local/include -DPREFIX='"/usr/local"' -DCHIPDB_SUBDIR='"icebox"'   -c -o timings-lp384.o timings-lp384.cc
timings-lp384.cc:233:3: error: use of undeclared identifier 'exit'
  exit(1);
  ^
1 error generated.
```

**Comment by cliffordwolf** [comment]
Added missing headers in aa5a623. Does this fix the issue for you?
