### ISSUE TITLE
Makefile assumes python binary is `python3`

### ISSUE THREAD

**Issue by xobs** [YosysHQ/icestorm#238]
The icebox `Makefile` calls `python3`, which is only the name of this program on Unix-like systems (according to PEP 394).  The official executable name on other platforms, notably on Windows, is `python`, and so the build fails on those platforms.

**Comment by xobs** [comment]
It's easy enough to add a variable to `config.mk` that lets you specify what python is called, which can get `icebox` to compile.  However, how much updating should we do?

Should `icefuzz` be updated to use $(PYTHON)?  What about `icetime`?  And what about various scripts such as `mktest.py`?

**Comment by mmicko** [comment]
Your fix have been merged, note change from PYTHON to PYTHON3
