### ISSUE TITLE
Lattice HX8K Breakout Board. Can not upload

### ISSUE THREAD

**Issue by Surac** [YosysHQ/icestorm#307]
Hallo.
I installed the libusbk Driver to the port 0 of the board, but i still cannot upload from the IDE.
Error message ist: Board not found.

i even installed the driver to port 1, but still no luck. 
Jumpers on the board are configured to programm the bitstream.

**Comment by gatecat** [comment]
What IDE?

**Comment by Surac** [comment]
Oh sorry. it is in Icestudio.

**Comment by gatecat** [comment]
Can you report this to icestudio? They are probably better placed to help here.

**Comment by Surac** [comment]
Sure, i was a litte confused where to post it.
Thank you
